readme: c-s frontend description
scylladb/cql-stress pull request #77
Opened 2024-05-08 15:41 UTC by muzarski

2024-05-21 11:01 UTC, soyacz commented
can you verify with user profiles in https://github.com/scylladb/scylla-qa-internal/tree/master repo if c-s frontend works with them?

2024-05-21 11:27 UTC, muzarski commented
CI fails due to clippy errors, see https://github.com/scylladb/cql-stress/pull/81

2024-05-21 12:00 UTC, wprzytula requested changes

2024-05-21 12:00 UTC, wprzytula commented on README.md
> +Since some of the options and paramters were not provided, the tool will make use of some default values. This will result in:
parameters

2024-05-21 12:00 UTC, wprzytula commented on README.md
> +To enable the `user` mode, the tool needs to be compiled with `user-profile` feature: `cargo build --release --features "user-profile"`
As @avelanarius mentioned, probably most of c-s users are using user profiles. Perhaps it makes sense then to make the feature turned on by default, so less fuss is needed for them.

2024-05-21 13:44 UTC, muzarski commented
v2:
- enabled `user-profile` feature by default
- adjusted CI
- added mention about available crate features in README

2024-05-21 14:30 UTC, wprzytula approved these changes

2024-05-22 11:51 UTC, muzarski commented
> can you verify with user profiles in https://github.com/scylladb/scylla-qa-internal/tree/master repo if c-s frontend works with them?

I see that user profiles in this repo make use of `insert` and `columnspec` parameters. These won't unfortunately be supported in the very first version of user profiles in cql-stress. I think that for `columnspec`, it will be easy to introduce it, since we already have the logic implemented.

2024-05-29 08:45 UTC, merged